use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "Bijwerken via WinGet";

pub(super) const STRINGS: Strings = Strings {
    locale_name: "nl-NL",
    window_title: "Gengchou",
    refresh: "Vernieuwen",
    refresh_now: "Nu vernieuwen",
    one_minute: "1 minuut",
    two_minutes: "2 minuten",
    five_minutes: "5 minuten",
    ten_minutes: "10 minuten",
    fifteen_minutes: "15 minuten",
    thirty_minutes: "30 minuten",
    models: "Aanbieders",
    claude_model: "Claude",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    grok_model: "Grok",
    settings: "Instellingen",
    settings_storage_failed: "Instellingen en gebruikscache konden niet worden opgeslagen.",
    start_with_windows: "Opstarten met Windows",
    widget_default_position: "Positie taakbalkwidget",
    floating_default_position: "Positie zwevend venster",
    primary_taskbar_left: "Linkerkant van taakbalk op hoofdscherm",
    primary_taskbar_right: "Rechterkant van taakbalk op hoofdscherm",
    primary_display_bottom_left: "Linksonder op hoofdscherm",
    primary_display_bottom_right: "Rechtsonder op hoofdscherm",
    language: "Taal",
    system_default: "Systeemstandaard",
    check_for_updates: "Controleren op updates",
    checking_for_updates: "Controleren op updates...",
    updates: "Updates",
    update_in_progress: "Er is al een updatecontrole bezig.",
    up_to_date: "Je gebruikt al de nieuwste versie.",
    up_to_date_short: "Up-to-date",
    update_failed: "Automatisch bijwerken mislukt",
    applying_update: "Update wordt toegepast...",
    update_to: "Bijwerken naar",
    update_available: "Update beschikbaar",
    update_prompt_now: "Versie {version} is beschikbaar. Wil je nu bijwerken?",
    exit: "Afsluiten",
    show_widget: "Taakbalkwidget",
    show_floating_monitor: "Zwevend venster",
    detailed_tray_icons: "Systeemvakpictogrammen per aanbieder",
    notifications: "Notifications",
    notify_session_reset: "Melding bij reset van korte limiet",
    notify_weekly_reset: "Melding bij reset van lange limiet",
    claude_cli_updated_title: "Claude Code bijgewerkt",
    claude_cli_updated_body: "Bijgewerkt van {before} naar {after}; authenticatie hersteld.",
    reset_notification_title: "Gebruiksvenster opnieuw ingesteld",
    reset_notification_body: "Het quotumvenster {window} van {provider} is opnieuw ingesteld.",
    session_window: "5h",
    weekly_window: "7d",
    quota_window: "Limiet",
    day_suffix: "d",
    hour_suffix: "u",
    minute_suffix: "m",
    second_suffix: "s",
    detail_waiting: "Wachten op gebruiksgegevens",
    detail_unavailable: "Kan gebruiksgegevens niet ophalen",
    detail_temporarily_unavailable: "Gebruiksgegevens tijdelijk niet beschikbaar",
    detail_pin_action: "Details open houden",
    detail_unpin_action: "Automatisch sluiten toestaan",
    detail_lock_position_action: "Vensterpositie vergrendelen",
    detail_unlock_position_action: "Venster verplaatsbaar maken",
    detail_close_action: "Details sluiten",
    detail_refreshing: "Bezig met vernieuwen",
    detail_network_action: "Controleer uw verbinding",
    detail_network_outcome: "Automatisch opnieuw proberen",
    detail_badge_auth_failed: "Aanmelding mislukt",
    detail_claude_login_action: "Meld u opnieuw aan bij Claude",
    detail_sign_in_again_action: "Meld u opnieuw aan bij {provider}",
    detail_monitoring_resumes: "Automatisch hervatten na aanmelden",
    detail_reset_unavailable: "Resettijd niet beschikbaar",
    detail_resets_in: "Reset over {duration}",
    detail_resets_now: "Wordt nu gereset",
    detail_updated_ago: "Laatst bijgewerkt, {ago} geleden",
    detail_next_in: "volgende over {next}",
    detail_poll_every: "Elke {interval}",
    detail_some_not_updated: "Sommige gebruiksgegevens zijn niet bijgewerkt",
    detail_all_not_updated: "Gebruiksgegevens zijn niet bijgewerkt",
    detail_badge_stale: "Vernieuwen mislukt",
    detail_badge_near_limit: "Bijna limiet",
    detail_badge_limit_reached: "Limiet bereikt",
    detail_badge_not_signed_in: "Niet gedetecteerd",
    detail_not_signed_in_action:
        "Wordt automatisch gedetecteerd nadat u zich bij {provider} aanmeldt",
    detail_access_revoked_hint: "Toegang tot {provider} geweigerd",
    detail_access_revoked_outcome: "Schakel deze weer in via het contextmenu",
    access_needs_review: "{provider} (controle nodig)",
    access_allow: "Toegang toestaan",
    access_keep_closed: "Gesloten houden",
    pending_access_title: "Gengchou toestaan {provider}-referenties te lezen?",
    pending_access_body: "Hiermee worden de lokale referenties van {provider} op deze computer gelezen en gebruikt om het verbruik te volgen. Dit verbruikt geen modeltegoed en aanmeldgegevens worden niet opgeslagen.\n\nU kunt dit later wijzigen via Providertoegang.",
    detail_access_pending_hint: "{provider} moet opnieuw worden beoordeeld",
    detail_access_pending_outcome: "Kies Toegang toestaan of Gesloten houden onder Providertoegang",
    provider_detected_title: "{provider} gedetecteerd",
    provider_detected_body: "Schakel deze in via het contextmenu om het gebruik te volgen.",
    redetect_providers: "Providers opnieuw detecteren",
    weekdays: ["zo", "ma", "di", "wo", "do", "vr", "za"],
};
