use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "Update via WinGet";

pub(super) const STRINGS: Strings = Strings {
    locale_name: "en-US",
    window_title: "Gengchou",
    refresh: "Refresh",
    refresh_now: "Refresh now",
    one_minute: "1 Minute",
    two_minutes: "2 Minutes",
    five_minutes: "5 Minutes",
    ten_minutes: "10 Minutes",
    fifteen_minutes: "15 Minutes",
    thirty_minutes: "30 Minutes",
    models: "Providers",
    claude_model: "Claude",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    grok_model: "Grok",
    settings: "Settings",
    settings_storage_failed: "Settings and cached usage could not be saved.",
    start_with_windows: "Start with Windows",
    widget_default_position: "Taskbar widget position",
    floating_default_position: "Floating window position",
    primary_taskbar_left: "Left Side of Primary Display Taskbar",
    primary_taskbar_right: "Right Side of Primary Display Taskbar",
    primary_display_bottom_left: "Bottom Left of Primary Display",
    primary_display_bottom_right: "Bottom Right of Primary Display",
    language: "Language",
    system_default: "System Default",
    check_for_updates: "Check for Updates",
    checking_for_updates: "Checking for Updates...",
    updates: "Updates",
    update_in_progress: "An update check is already in progress.",
    up_to_date: "You already have the latest version.",
    up_to_date_short: "Up to date",
    update_failed: "Unable to update automatically",
    applying_update: "Applying update...",
    update_to: "Update to",
    update_available: "Update available",
    update_prompt_now: "Version {version} is available. Do you want to update now?",
    exit: "Exit",
    show_widget: "Taskbar widget",
    show_floating_monitor: "Floating window",
    detailed_tray_icons: "Provider tray icons",
    notifications: "Notifications",
    notify_session_reset: "Notify on short-window reset",
    notify_weekly_reset: "Notify on long-window reset",
    claude_cli_updated_title: "Claude Code updated",
    claude_cli_updated_body: "Updated from {before} to {after}; authentication recovered.",
    reset_notification_title: "Usage window reset",
    reset_notification_body: "{provider} {window} quota has reset.",
    session_window: "5h",
    weekly_window: "7d",
    quota_window: "Quota",
    day_suffix: "d",
    hour_suffix: "h",
    minute_suffix: "m",
    second_suffix: "s",
    detail_waiting: "Waiting for usage data",
    detail_unavailable: "Unable to get usage data",
    detail_temporarily_unavailable: "Usage temporarily unavailable",
    detail_pin_action: "Keep details open",
    detail_unpin_action: "Allow automatic closing",
    detail_lock_position_action: "Lock window position",
    detail_unlock_position_action: "Allow window movement",
    detail_close_action: "Close details",
    detail_refreshing: "Refreshing",
    detail_network_action: "Check your connection",
    detail_network_outcome: "Retrying automatically",
    detail_badge_auth_failed: "Authentication failed",
    detail_claude_login_action: "Sign in to Claude again",
    detail_sign_in_again_action: "Sign in to {provider} again",
    detail_monitoring_resumes: "Automatically resumes after sign-in",
    detail_reset_unavailable: "Reset time unavailable",
    detail_resets_in: "Resets in {duration}",
    detail_resets_now: "Resets now",
    detail_updated_ago: "Last updated {ago} ago",
    detail_next_in: "next in {next}",
    detail_poll_every: "Every {interval}",
    detail_some_not_updated: "Some usage data was not updated",
    detail_all_not_updated: "Usage data was not updated",
    detail_badge_stale: "Refresh failed",
    detail_badge_near_limit: "Near limit",
    detail_badge_limit_reached: "Limit reached",
    detail_badge_not_signed_in: "Not detected",
    detail_not_signed_in_action: "Detected automatically after you sign in to {provider}",
    detail_access_revoked_hint: "Gengchou has no access to {provider}",
    detail_access_revoked_outcome: "Allow it under Provider access",
    access_needs_review: "{provider} (needs review)",
    access_allow: "Allow access",
    access_keep_closed: "Keep closed",
    access_decide_later: "Decide later",
    pending_access_title: "Allow Gengchou to read {provider} credentials?",
    pending_access_body: "This reads {provider}'s local credentials on this machine and uses them to monitor usage. It does not consume model allowance and does not store sign-in information.\n\nYou can change this later from Provider access.",
    detail_access_pending_hint: "{provider} needs an access review",
    detail_access_pending_outcome: "Choose Allow access or Keep closed under Provider access",
    provider_detected_title: "{provider} detected",
    provider_detected_body: "Enable it from the context menu to monitor its usage.",
    redetect_providers: "Detect providers again",
    weekdays: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
};
