use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "Mettre à jour avec WinGet";

pub(super) const STRINGS: Strings = Strings {
    locale_name: "fr-FR",
    window_title: "Gengchou",
    refresh: "Actualiser",
    refresh_now: "Actualiser maintenant",
    one_minute: "1 minute",
    two_minutes: "2 minutes",
    five_minutes: "5 minutes",
    ten_minutes: "10 minutes",
    fifteen_minutes: "15 minutes",
    thirty_minutes: "30 minutes",
    models: "Fournisseurs",
    claude_model: "Claude",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    settings: "Paramètres",
    settings_storage_failed:
        "Les paramètres et les données d’utilisation en cache n’ont pas pu être enregistrés.",
    start_with_windows: "Démarrer avec Windows",
    widget_default_position: "Position du widget de la barre des tâches",
    floating_default_position: "Position de la fenêtre flottante",
    primary_taskbar_left: "À gauche de la barre des tâches principale",
    primary_taskbar_right: "À droite de la barre des tâches principale",
    primary_display_bottom_left: "En bas à gauche de l’écran principal",
    primary_display_bottom_right: "En bas à droite de l’écran principal",
    language: "Langue",
    system_default: "Par défaut du système",
    check_for_updates: "Vérifier les mises à jour",
    checking_for_updates: "Vérification des mises à jour...",
    updates: "Mises à jour",
    update_in_progress: "Une vérification de mise à jour est déjà en cours.",
    up_to_date: "Vous utilisez déjà la version la plus récente.",
    up_to_date_short: "À jour",
    update_failed: "Impossible d’effectuer la mise à jour automatiquement",
    applying_update: "Application de la mise à jour...",
    update_to: "Mettre à jour vers",
    update_available: "Mise à jour disponible",
    update_prompt_now:
        "La version {version} est disponible. Voulez-vous mettre à jour maintenant ?",
    exit: "Quitter",
    show_widget: "Widget de la barre des tâches",
    show_floating_monitor: "Fenêtre flottante",
    detailed_tray_icons: "Icônes des fournisseurs dans la zone de notification",
    notifications: "Notifications",
    notify_session_reset: "Notifier la réinitialisation de limite courte",
    notify_weekly_reset: "Notifier la réinitialisation de limite longue",
    claude_cli_updated_title: "Claude Code mis à jour",
    claude_cli_updated_body: "Mise à jour de {before} vers {after} ; authentification restaurée.",
    reset_notification_title: "Fenêtre d’utilisation réinitialisée",
    reset_notification_body: "Le quota {window} de {provider} a été réinitialisé.",
    session_window: "5h",
    weekly_window: "7d",
    quota_window: "Quota",
    day_suffix: "j",
    hour_suffix: "h",
    minute_suffix: "m",
    second_suffix: "s",
    detail_waiting: "En attente des données d’utilisation",
    detail_unavailable: "Impossible d’obtenir les données d’utilisation",
    detail_temporarily_unavailable: "Données d’utilisation temporairement indisponibles",
    detail_pin_action: "Maintenir les détails ouverts",
    detail_unpin_action: "Autoriser la fermeture automatique",
    detail_lock_position_action: "Verrouiller la position",
    detail_unlock_position_action: "Autoriser le déplacement",
    detail_close_action: "Fermer les détails",
    detail_refreshing: "Actualisation",
    detail_network_action: "Vérifiez la connexion",
    detail_network_outcome: "Nouvel essai automatique en cours",
    detail_badge_auth_failed: "Authentification échouée",
    detail_claude_login_action: "Reconnectez-vous à Claude",
    detail_sign_in_again_action: "Reconnectez-vous à {provider}",
    detail_monitoring_resumes: "Reprise automatique après connexion",
    detail_reset_unavailable: "Heure de réinitialisation indisponible",
    detail_resets_in: "Réinitialisation dans {duration}",
    detail_resets_now: "Réinitialisation en cours",
    detail_updated_ago: "Dernière mise à jour il y a {ago}",
    detail_next_in: "prochaine dans {next}",
    detail_poll_every: "Toutes les {interval}",
    detail_some_not_updated: "Certaines données d’utilisation n’ont pas été actualisées",
    detail_all_not_updated: "Les données d’utilisation n’ont pas été actualisées",
    detail_badge_stale: "Échec de l’actualisation",
    detail_badge_near_limit: "Proche de la limite",
    detail_badge_limit_reached: "Limite atteinte",
    detail_badge_not_signed_in: "Non détecté",
    detail_not_signed_in_action: "Détecté automatiquement après votre connexion à {provider}",
    detail_access_revoked_hint: "Accès à {provider} refusé",
    detail_access_revoked_outcome: "Réactivez-le dans le menu contextuel",
    provider_detected_title: "{provider} détecté",
    provider_detected_body: "Activez-le depuis le menu contextuel pour surveiller son utilisation.",
    redetect_providers: "Redétecter les fournisseurs",
    weekdays: ["dim.", "lun.", "mar.", "mer.", "jeu.", "ven.", "sam."],
};
