use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "Mit WinGet aktualisieren";

pub(super) const STRINGS: Strings = Strings {
    locale_name: "de-DE",
    window_title: "Gengchou",
    refresh: "Aktualisieren",
    refresh_now: "Jetzt aktualisieren",
    one_minute: "1 Minute",
    two_minutes: "2 Minuten",
    five_minutes: "5 Minuten",
    ten_minutes: "10 Minuten",
    fifteen_minutes: "15 Minuten",
    thirty_minutes: "30 Minuten",
    models: "Anbieter",
    claude_model: "Claude",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    grok_model: "Grok",
    settings: "Einstellungen",
    settings_storage_failed:
        "Einstellungen und zwischengespeicherte Nutzungsdaten konnten nicht gespeichert werden.",
    start_with_windows: "Mit Windows starten",
    widget_default_position: "Position des Taskleisten-Widgets",
    floating_default_position: "Position des schwebenden Fensters",
    primary_taskbar_left: "Linke Seite der Taskleiste auf dem Hauptbildschirm",
    primary_taskbar_right: "Rechte Seite der Taskleiste auf dem Hauptbildschirm",
    primary_display_bottom_left: "Unten links auf dem Hauptbildschirm",
    primary_display_bottom_right: "Unten rechts auf dem Hauptbildschirm",
    language: "Sprache",
    system_default: "Systemstandard",
    check_for_updates: "Nach Updates suchen",
    checking_for_updates: "Suche nach Updates...",
    updates: "Updates",
    update_in_progress: "Eine Update-Prüfung läuft bereits.",
    up_to_date: "Sie verwenden bereits die neueste Version.",
    up_to_date_short: "Aktuell",
    update_failed: "Automatisches Update war nicht möglich",
    applying_update: "Update wird installiert...",
    update_to: "Aktualisieren auf",
    update_available: "Update verfügbar",
    update_prompt_now: "Version {version} ist verfügbar. Möchten Sie jetzt aktualisieren?",
    exit: "Beenden",
    show_widget: "Taskleisten-Widget",
    show_floating_monitor: "Schwebendes Fenster",
    detailed_tray_icons: "Anbietersymbole im Infobereich",
    notifications: "Notifications",
    notify_session_reset: "Bei Rücksetzung kurzer Limits benachrichtigen",
    notify_weekly_reset: "Bei Rücksetzung langer Limits benachrichtigen",
    claude_cli_updated_title: "Claude Code aktualisiert",
    claude_cli_updated_body:
        "Von {before} auf {after} aktualisiert; Authentifizierung wiederhergestellt.",
    reset_notification_title: "Nutzungszeitraum zurückgesetzt",
    reset_notification_body: "Das {window}-Kontingent von {provider} wurde zurückgesetzt.",
    session_window: "5h",
    weekly_window: "7d",
    quota_window: "Limit",
    day_suffix: "T",
    hour_suffix: "h",
    minute_suffix: "m",
    second_suffix: "s",
    detail_waiting: "Warte auf Nutzungsdaten",
    detail_unavailable: "Nutzungsdaten können nicht abgerufen werden",
    detail_temporarily_unavailable: "Nutzungsdaten vorübergehend nicht verfügbar",
    detail_pin_action: "Details geöffnet halten",
    detail_unpin_action: "Automatisches Schließen zulassen",
    detail_lock_position_action: "Fensterposition sperren",
    detail_unlock_position_action: "Fenster verschiebbar machen",
    detail_close_action: "Details schließen",
    detail_refreshing: "Aktualisierung läuft",
    detail_network_action: "Verbindung prüfen",
    detail_network_outcome: "Automatischer Neuversuch läuft",
    detail_badge_auth_failed: "Login fehlgeschlagen",
    detail_claude_login_action: "Melden Sie sich erneut bei Claude an",
    detail_sign_in_again_action: "Melden Sie sich erneut bei {provider} an",
    detail_monitoring_resumes: "Nach der Anmeldung automatisch fortsetzen",
    detail_reset_unavailable: "Rücksetzzeit nicht verfügbar",
    detail_resets_in: "Wird in {duration} zurückgesetzt",
    detail_resets_now: "Wird jetzt zurückgesetzt",
    detail_updated_ago: "Zuletzt vor {ago} aktualisiert",
    detail_next_in: "nächste in {next}",
    detail_poll_every: "Alle {interval}",
    detail_some_not_updated: "Einige Nutzungsdaten wurden nicht aktualisiert",
    detail_all_not_updated: "Nutzungsdaten wurden nicht aktualisiert",
    detail_badge_stale: "Aktualisierung fehlgeschlagen",
    detail_badge_near_limit: "Nahe am Limit",
    detail_badge_limit_reached: "Limit erreicht",
    detail_badge_not_signed_in: "Nicht erkannt",
    detail_not_signed_in_action: "Wird nach der Anmeldung bei {provider} automatisch erkannt",
    detail_access_revoked_hint: "Kein Zugriff auf {provider}",
    detail_access_revoked_outcome: "Unter „Anbieterzugriff“ erlauben",
    access_needs_review: "{provider} (Prüfung erforderlich)",
    access_allow: "Zugriff erlauben",
    access_keep_closed: "Geschlossen lassen",
    access_decide_later: "Später entscheiden",
    pending_access_title: "Gengchou erlauben, {provider}-Anmeldedaten zu lesen?",
    pending_access_body: "Damit werden die lokalen Anmeldedaten von {provider} auf diesem Computer gelesen und zur Nutzungsüberwachung verwendet. Es wird kein Modellkontingent verbraucht, und Ihre Anmeldedaten werden nicht gespeichert.\n\nSie können dies später unter „Anbieterzugriff“ ändern.",
    detail_access_pending_hint: "{provider} muss erneut geprüft werden",
    detail_access_pending_outcome: "Wählen Sie unter Anbieterzugriff „Zugriff erlauben“ oder „Geschlossen lassen“",
    provider_detected_title: "{provider} erkannt",
    provider_detected_body: "Im Kontextmenü aktivieren, um die Nutzung zu überwachen.",
    redetect_providers: "Anbieter erneut suchen",
    weekdays: ["So", "Mo", "Di", "Mi", "Do", "Fr", "Sa"],
};
