use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "WinGet で更新";

pub(super) const STRINGS: Strings = Strings {
    locale_name: "ja-JP",
    window_title: "Gengchou",
    refresh: "更新",
    refresh_now: "今すぐ更新",
    one_minute: "1分",
    two_minutes: "2分",
    five_minutes: "5分",
    ten_minutes: "10分",
    fifteen_minutes: "15分",
    thirty_minutes: "30分",
    models: "プロバイダー",
    claude_model: "Claude",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    grok_model: "Grok",
    settings: "設定",
    settings_storage_failed: "設定とキャッシュされた使用量データを保存できませんでした。",
    start_with_windows: "Windows と同時に開始",
    widget_default_position: "タスクバー ウィジェットの位置",
    floating_default_position: "フローティングウィンドウの位置",
    primary_taskbar_left: "メイン画面のタスクバー左側",
    primary_taskbar_right: "メイン画面のタスクバー右側",
    primary_display_bottom_left: "メイン画面の左下",
    primary_display_bottom_right: "メイン画面の右下",
    language: "言語",
    system_default: "システム既定",
    check_for_updates: "更新を確認",
    checking_for_updates: "更新を確認しています...",
    updates: "更新",
    update_in_progress: "更新確認は既に実行中です。",
    up_to_date: "既に最新バージョンです。",
    up_to_date_short: "最新です",
    update_failed: "自動更新を完了できませんでした",
    applying_update: "更新を適用しています...",
    update_to: "更新先",
    update_available: "更新が利用可能です",
    update_prompt_now: "バージョン {version} が利用可能です。今すぐ更新しますか？",
    exit: "終了",
    show_widget: "タスクバー ウィジェット",
    show_floating_monitor: "フローティングウィンドウ",
    detailed_tray_icons: "プロバイダー別の通知領域アイコン",
    notifications: "Notifications",
    notify_session_reset: "短期枠のリセットを通知",
    notify_weekly_reset: "長期枠のリセットを通知",
    claude_cli_updated_title: "Claude Code を更新しました",
    claude_cli_updated_body: "{before} から {after} に更新し、認証を復旧しました。",
    reset_notification_title: "使用量ウィンドウをリセットしました",
    reset_notification_body: "{provider} の {window} クォータがリセットされました。",
    session_window: "5h",
    weekly_window: "7d",
    quota_window: "上限",
    day_suffix: "日",
    hour_suffix: "時間",
    minute_suffix: "分",
    second_suffix: "秒",
    detail_waiting: "使用量データを待機中",
    detail_unavailable: "使用量データを取得できません",
    detail_temporarily_unavailable: "使用量データを一時的に取得できません",
    detail_pin_action: "詳細を開いたままにする",
    detail_unpin_action: "自動的に閉じる",
    detail_lock_position_action: "ウィンドウ位置をロック",
    detail_unlock_position_action: "ウィンドウの移動を許可",
    detail_close_action: "詳細を閉じる",
    detail_refreshing: "更新中",
    detail_network_action: "接続を確認してください",
    detail_network_outcome: "自動的に再試行中",
    detail_badge_auth_failed: "認証に失敗",
    detail_claude_login_action: "Claude に再度サインイン",
    detail_sign_in_again_action: "{provider} に再度サインイン",
    detail_monitoring_resumes: "ログイン後に自動復旧",
    detail_reset_unavailable: "リセット時刻を取得できません",
    detail_resets_in: "{duration}後にリセット",
    detail_resets_now: "まもなくリセット",
    detail_updated_ago: "最終更新: {ago}前",
    detail_next_in: "次回更新まで {next}",
    detail_poll_every: "更新間隔 {interval}",
    detail_some_not_updated: "一部の使用量データを更新できませんでした",
    detail_all_not_updated: "使用量データを更新できませんでした",
    detail_badge_stale: "更新に失敗",
    detail_badge_near_limit: "上限間近",
    detail_badge_limit_reached: "上限に到達",
    detail_badge_not_signed_in: "未検出",
    detail_not_signed_in_action: "{provider} にサインインすると自動的に検出されます",
    detail_access_revoked_hint: "{provider} へのアクセス権がありません",
    detail_access_revoked_outcome: "「プロバイダーへのアクセス」で許可できます",
    access_needs_review: "{provider}（要確認）",
    access_allow: "アクセスを許可",
    access_keep_closed: "閉じたままにする",
    access_decide_later: "後で決める",
    pending_access_title: "Gengchou に {provider} の資格情報の読み取りを許可しますか？",
    pending_access_body: "このコンピューター上の {provider} のローカル資格情報を読み取り、使用量の監視に使います。モデルの利用枠は消費せず、サインイン情報も保存しません。\n\n後から「プロバイダーへのアクセス」で変更できます。",
    detail_access_pending_hint: "{provider} のアクセス確認が必要です",
    detail_access_pending_outcome: "「プロバイダーへのアクセス」で許可するか閉じたままにするか選んでください",
    provider_detected_title: "{provider} を検出しました",
    provider_detected_body: "コンテキスト メニューから有効にすると使用量を監視できます。",
    redetect_providers: "プロバイダーを再検出",
    weekdays: ["日", "月", "火", "水", "木", "金", "土"],
};
