use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "WinGet으로 업데이트";

pub(super) const STRINGS: Strings = Strings {
    locale_name: "ko-KR",
    window_title: "Gengchou",
    instance_already_running:
        "Gengchou가 이미 사용자의 설정을 사용하여 실행 중입니다. 이 PC의 다른 Windows 세션일 가능성이 높습니다. 한 번에 하나만 사용할 수 있습니다.",
    instance_lock_failed: "Gengchou를 시작할 수 없습니다: 단일 인스턴스 잠금을 만들지 못했습니다.",
    diagnostics_unavailable: "진단 로그를 사용할 수 없으므로 충돌을 포함한 문제가 이 PC에 전혀 기록되지 않습니다.",
    refresh: "새로고침",
    refresh_now: "지금 새로 고침",
    one_minute: "1분",
    two_minutes: "2분",
    five_minutes: "5분",
    ten_minutes: "10분",
    fifteen_minutes: "15분",
    thirty_minutes: "30분",
    models: "서비스",
    claude_model: "Claude",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    grok_model: "Grok",
    settings: "설정",
    settings_storage_failed: "설정과 캐시된 사용량 데이터를 저장할 수 없습니다.",
    start_with_windows: "Windows 시작 시 자동 실행",
    widget_default_position: "작업 표시줄 위젯 위치",
    floating_default_position: "플로팅 창 위치",
    primary_taskbar_left: "기본 화면 작업 표시줄 왼쪽",
    primary_taskbar_right: "기본 화면 작업 표시줄 오른쪽",
    primary_display_bottom_left: "기본 화면 왼쪽 아래",
    primary_display_bottom_right: "기본 화면 오른쪽 아래",
    language: "언어",
    system_default: "시스템 기본값",
    check_for_updates: "업데이트 확인",
    checking_for_updates: "업데이트 확인 중...",
    updates: "업데이트",
    update_in_progress: "이미 업데이트 확인이 진행 중입니다.",
    up_to_date: "이미 최신 버전입니다.",
    up_to_date_short: "최신",
    update_failed: "자동 업데이트를 완료할 수 없습니다",
    applying_update: "업데이트 적용 중...",
    update_to: "업데이트 대상",
    update_available: "업데이트 사용 가능",
    update_prompt_now: "버전 {version}을 사용할 수 있습니다. 지금 업데이트하시겠습니까?",
    update_available_balloon_body: "버전 {version}을(를) 사용할 수 있습니다. 트레이 메뉴의 ‘{settings}’에서 업데이트하세요.",
    exit: "종료",
    show_widget: "작업 표시줄 위젯",
    show_floating_monitor: "플로팅 창",
    detailed_tray_icons: "서비스별 알림 영역 아이콘",
    notifications: "Notifications",
    notify_session_reset: "단기 한도 초기화 알림",
    notify_weekly_reset: "장기 한도 초기화 알림",
    claude_cli_updated_title: "Claude Code 업데이트됨",
    claude_cli_updated_body: "{before}에서 {after}(으)로 업데이트하고 인증을 복구했습니다.",
    reset_notification_title: "사용량 기간이 초기화됨",
    reset_notification_body: "{provider}의 {window} 할당량이 초기화되었습니다.",
    session_window: "5h",
    weekly_window: "7d",
    quota_window: "한도",
    day_suffix: "일",
    hour_suffix: "시간",
    minute_suffix: "분",
    second_suffix: "초",
    detail_waiting: "사용량 데이터 대기 중",
    detail_unavailable: "사용량 데이터를 가져올 수 없음",
    detail_temporarily_unavailable: "사용량 데이터를 일시적으로 가져올 수 없음",
    detail_pin_action: "세부 정보를 열린 상태로 유지",
    detail_unpin_action: "자동 닫기 허용",
    detail_lock_position_action: "창 위치 잠금",
    detail_unlock_position_action: "창 이동 허용",
    detail_close_action: "세부 정보 닫기",
    detail_refreshing: "새로 고치는 중",
    detail_network_action: "연결을 확인하세요",
    detail_network_outcome: "자동으로 다시 시도 중",
    detail_badge_auth_failed: "인증 실패",
    detail_claude_login_action: "Claude에 다시 로그인하세요",
    detail_sign_in_again_action: "{provider}에 다시 로그인하세요",
    detail_monitoring_resumes: "로그인 후 자동 복구",
    detail_reset_unavailable: "재설정 시간을 확인할 수 없음",
    detail_resets_in: "{duration} 후 재설정",
    detail_resets_now: "곧 재설정",
    detail_updated_ago: "마지막 업데이트: {ago} 전",
    detail_next_in: "다음 업데이트까지 {next}",
    detail_poll_every: "{interval}마다",
    detail_some_not_updated: "일부 사용량 데이터가 업데이트되지 않음",
    detail_all_not_updated: "사용량 데이터가 업데이트되지 않음",
    detail_badge_stale: "새로 고침 실패",
    detail_badge_near_limit: "한도 임박",
    detail_badge_limit_reached: "한도 도달",
    detail_badge_not_signed_in: "감지되지 않음",
    detail_not_signed_in_action: "{provider}에 로그인하면 자동으로 감지됩니다",
    detail_access_revoked_hint: "{provider}에 대한 액세스 권한이 없습니다",
    detail_access_revoked_outcome: "'공급자 액세스'에서 허용할 수 있습니다",
    access_needs_review: "{provider} (검토 필요)",
    access_allow: "액세스 허용",
    access_keep_closed: "닫힌 상태 유지",
    access_decide_later: "나중에 결정",
    pending_access_title: "Gengchou가 {provider} 자격 증명을 읽도록 허용하시겠습니까?",
    pending_access_body: "이 컴퓨터에 있는 {provider}의 로컬 자격 증명을 읽어 사용량 모니터링에 사용합니다. 모델 할당량을 소비하지 않으며 로그인 정보를 저장하지도 않습니다.\n\n나중에 '공급자 액세스'에서 변경할 수 있습니다.",
    detail_access_pending_hint: "{provider} 액세스 검토가 필요합니다",
    detail_access_pending_outcome: "공급자 액세스에서 액세스 허용 또는 닫힌 상태 유지를 선택하세요",
    provider_detected_title: "{provider}을(를) 감지했습니다",
    provider_detected_body: "상황에 맞는 메뉴에서 활성화하면 사용량을 모니터링합니다.",
    redetect_providers: "공급자 다시 감지",
    weekdays: ["일", "월", "화", "수", "목", "금", "토"],
};
