use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "Atualizar via WinGet";

pub(super) const STRINGS: Strings = Strings {
    locale_name: "pt-BR",
    window_title: "Gengchou",
    instance_already_running:
        "O Gengchou já está em execução em outra sessão do Windows neste PC. Apenas um Gengchou por vez pode usar suas configurações.",
    instance_lock_failed:
        "O Gengchou não pôde ser iniciado: não foi possível criar o bloqueio de instância única.",
    diagnostics_unavailable:
        "O registro de diagnostico esta indisponivel, portanto problemas, inclusive falhas, nao deixarao rastro neste PC.",
    refresh: "Atualizar",
    refresh_now: "Atualizar agora",
    one_minute: "1 Minuto",
    two_minutes: "2 Minutos",
    five_minutes: "5 Minutos",
    ten_minutes: "10 Minutos",
    fifteen_minutes: "15 Minutos",
    thirty_minutes: "30 Minutos",
    models: "Provedores",
    claude_model: "Claude",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    grok_model: "Grok",
    settings: "Configurações",
    settings_storage_failed: "Não foi possível salvar as configurações e os dados de uso em cache.",
    start_with_windows: "Iniciar com o Windows",
    widget_default_position: "Posição do widget da barra de tarefas",
    floating_default_position: "Posição da janela flutuante",
    primary_taskbar_left: "Lado esquerdo da barra de tarefas da tela principal",
    primary_taskbar_right: "Lado direito da barra de tarefas da tela principal",
    primary_display_bottom_left: "Canto inferior esquerdo da tela principal",
    primary_display_bottom_right: "Canto inferior direito da tela principal",
    language: "Idioma",
    system_default: "Padrão do Sistema",
    check_for_updates: "Busca atualizações",
    checking_for_updates: "Buscando por atualizações...",
    updates: "Atualizações",
    update_in_progress: "Uma verificação de atualização já está em andamento.",
    up_to_date: "Você já tem a versão mais recente.",
    up_to_date_short: "Atualizado",
    update_failed: "Não foi possível atualizar automaticamente",
    applying_update: "Aplicando atualização...",
    update_to: "Atualizar para",
    update_available: "Atualização disponível",
    update_prompt_now: "Versão {version} está disponível. Deseja atualizar agora?",
    exit: "Sair",
    show_widget: "Widget da barra de tarefas",
    show_floating_monitor: "Janela flutuante",
    detailed_tray_icons: "Ícones dos provedores na bandeja",
    notifications: "Notifications",
    notify_session_reset: "Notificar ao redefinir limite curto",
    notify_weekly_reset: "Notificar ao redefinir limite longo",
    claude_cli_updated_title: "Claude Code atualizado",
    claude_cli_updated_body: "Atualizado de {before} para {after}; autenticação recuperada.",
    reset_notification_title: "Período de uso redefinido",
    reset_notification_body: "A cota {window} de {provider} foi redefinida.",
    session_window: "5h",
    weekly_window: "7d",
    quota_window: "Cota",
    day_suffix: "d",
    hour_suffix: "h",
    minute_suffix: "m",
    second_suffix: "s",
    detail_waiting: "Aguardando dados de uso",
    detail_unavailable: "Não foi possível obter os dados de uso",
    detail_temporarily_unavailable: "Dados de uso temporariamente indisponíveis",
    detail_pin_action: "Manter detalhes abertos",
    detail_unpin_action: "Permitir fechamento automático",
    detail_lock_position_action: "Bloquear posição da janela",
    detail_unlock_position_action: "Permitir mover a janela",
    detail_close_action: "Fechar detalhes",
    detail_refreshing: "Atualizando",
    detail_network_action: "Verifique a conexão",
    detail_network_outcome: "Tentando novamente automaticamente",
    detail_badge_auth_failed: "Autenticação falhou",
    detail_claude_login_action: "Entre novamente no Claude",
    detail_sign_in_again_action: "Entre novamente no {provider}",
    detail_monitoring_resumes: "Retoma automaticamente após o login",
    detail_reset_unavailable: "Horário de redefinição indisponível",
    detail_resets_in: "Redefine em {duration}",
    detail_resets_now: "Redefine agora",
    detail_updated_ago: "Última atualização há {ago}",
    detail_next_in: "próxima em {next}",
    detail_poll_every: "A cada {interval}",
    detail_some_not_updated: "Alguns dados de uso não foram atualizados",
    detail_all_not_updated: "Os dados de uso não foram atualizados",
    detail_badge_stale: "Falha na atualização",
    detail_badge_near_limit: "Próximo do limite",
    detail_badge_limit_reached: "Limite atingido",
    detail_badge_not_signed_in: "Não detectado",
    detail_not_signed_in_action: "Detectado automaticamente após você entrar no {provider}",
    detail_access_revoked_hint: "Sem acesso ao {provider}",
    detail_access_revoked_outcome: "Permita em Acesso aos provedores",
    access_needs_review: "{provider} (precisa de revisão)",
    access_allow: "Permitir acesso",
    access_keep_closed: "Manter fechado",
    access_decide_later: "Decidir depois",
    pending_access_title: "Permitir que o Gengchou leia as credenciais de {provider}?",
    pending_access_body: "Isso lê as credenciais locais de {provider} neste computador e as usa para monitorar o uso. Não consome cota de modelo nem armazena informações de login.\n\nVocê pode alterar isso depois em Acesso aos provedores.",
    detail_access_pending_hint: "{provider} precisa de uma revisão de acesso",
    detail_access_pending_outcome: "Escolha Permitir acesso ou Manter fechado em Acesso aos provedores",
    provider_detected_title: "{provider} detectado",
    provider_detected_body: "Ative-o no menu de contexto para monitorar o uso.",
    redetect_providers: "Detectar provedores novamente",
    weekdays: ["dom", "seg", "ter", "qua", "qui", "sex", "sáb"],
};
