use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "Обновить через WinGet";

pub(super) const STRINGS: Strings = Strings {
    locale_name: "ru-RU",
    window_title: "Gengchou",
    refresh: "Обновить",
    refresh_now: "Обновить сейчас",
    one_minute: "1 минута",
    two_minutes: "2 минуты",
    five_minutes: "5 минут",
    ten_minutes: "10 минут",
    fifteen_minutes: "15 минут",
    thirty_minutes: "30 минут",
    models: "Провайдеры",
    claude_model: "Claude",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    settings: "Настройки",
    settings_storage_failed:
        "Не удалось сохранить настройки и кэшированные данные об использовании.",
    start_with_windows: "Запускать вместе с Windows",
    widget_default_position: "Положение виджета панели задач",
    floating_default_position: "Положение плавающего окна",
    primary_taskbar_left: "Слева на панели задач основного экрана",
    primary_taskbar_right: "Справа на панели задач основного экрана",
    primary_display_bottom_left: "Внизу слева на основном экране",
    primary_display_bottom_right: "Внизу справа на основном экране",
    language: "Язык",
    system_default: "Системный по умолчанию",
    check_for_updates: "Проверить обновления",
    checking_for_updates: "Проверка обновлений...",
    updates: "Обновления",
    update_in_progress: "Проверка обновлений уже выполняется.",
    up_to_date: "У вас уже установлена последняя версия.",
    up_to_date_short: "Актуальная версия",
    update_failed: "Не удалось обновить автоматически",
    applying_update: "Применение обновления...",
    update_to: "Обновить до",
    update_available: "Доступно обновление",
    update_prompt_now: "Доступна версия {version}. Обновить сейчас?",
    exit: "Выход",
    show_widget: "Виджет панели задач",
    show_floating_monitor: "Плавающее окно",
    detailed_tray_icons: "Значки провайдеров в области уведомлений",
    notifications: "Notifications",
    notify_session_reset: "Уведомлять о сбросе краткого лимита",
    notify_weekly_reset: "Уведомлять о сбросе долгого лимита",
    notify_claude_cli_update: "Уведомлять об обновлении Claude Code",
    claude_cli_updated_title: "Claude Code обновлён",
    claude_cli_updated_body: "Обновлено с {before} до {after}; аутентификация восстановлена.",
    reset_notification_title: "Период использования сброшен",
    reset_notification_body: "Квота {provider} за период {window} сброшена.",
    session_window: "5h",
    weekly_window: "7d",
    quota_window: "Лимит",
    day_suffix: "д",
    hour_suffix: "ч",
    minute_suffix: "м",
    second_suffix: "с",
    detail_waiting: "Ожидание данных об использовании",
    detail_unavailable: "Не удалось получить данные об использовании",
    detail_temporarily_unavailable: "Данные об использовании временно недоступны",
    detail_pin_action: "Оставить сведения открытыми",
    detail_unpin_action: "Разрешить автозакрытие",
    detail_lock_position_action: "Заблокировать положение окна",
    detail_unlock_position_action: "Разрешить перемещение окна",
    detail_close_action: "Закрыть сведения",
    detail_refreshing: "Обновление",
    detail_network_action: "Проверьте подключение",
    detail_network_outcome: "Автоматическая повторная попытка",
    detail_badge_auth_failed: "Ошибка входа",
    detail_claude_login_action: "Снова войдите в Claude",
    detail_sign_in_again_action: "Снова войдите в {provider}",
    detail_monitoring_resumes: "Автоматически продолжит после входа",
    detail_reset_unavailable: "Время сброса недоступно",
    detail_resets_in: "Сброс через {duration}",
    detail_resets_now: "Сброс сейчас",
    detail_updated_ago: "Последнее обновление {ago} назад",
    detail_next_in: "следующее через {next}",
    detail_poll_every: "Каждые {interval}",
    detail_some_not_updated: "Некоторые данные об использовании не обновлены",
    detail_all_not_updated: "Данные об использовании не обновлены",
    detail_badge_stale: "Сбой обновления",
    detail_badge_near_limit: "Почти достигнут лимит",
    detail_badge_limit_reached: "Лимит достигнут",
    detail_badge_not_signed_in: "Не обнаружено",
    detail_not_signed_in_action: "Будет обнаружено автоматически после входа в {provider}",
    detail_access_revoked_hint: "Доступ к {provider} отклонён",
    detail_access_revoked_outcome: "Включите его снова в контекстном меню",
    provider_detected_title: "Обнаружен {provider}",
    provider_detected_body: "Включите его в контекстном меню, чтобы отслеживать использование.",
    redetect_providers: "Обнаружить провайдеров заново",
    weekdays: ["вс", "пн", "вт", "ср", "чт", "пт", "сб"],
};
