use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "通过 WinGet 更新";

pub(super) const STRINGS: Strings = Strings {
    locale_name: "zh-CN",
    window_title: "更筹",
    refresh: "刷新",
    refresh_now: "立即刷新",
    one_minute: "1 分钟",
    two_minutes: "2 分钟",
    five_minutes: "5 分钟",
    ten_minutes: "10 分钟",
    fifteen_minutes: "15 分钟",
    thirty_minutes: "30 分钟",
    models: "服务商",
    claude_model: "Claude",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    grok_model: "Grok",
    settings: "设置",
    settings_storage_failed: "无法保存设置和缓存的用量数据。",
    start_with_windows: "开机启动",
    widget_default_position: "任务栏小组件位置",
    floating_default_position: "桌面浮窗位置",
    primary_taskbar_left: "主屏幕任务栏左侧",
    primary_taskbar_right: "主屏幕任务栏右侧",
    primary_display_bottom_left: "主屏幕左下角",
    primary_display_bottom_right: "主屏幕右下角",
    language: "语言",
    system_default: "跟随系统",
    check_for_updates: "检查更新",
    checking_for_updates: "正在检查更新...",
    updates: "更新",
    update_in_progress: "更新检查已在进行中。",
    up_to_date: "当前已是最新版本。",
    up_to_date_short: "已是最新",
    update_failed: "无法自动更新",
    applying_update: "正在应用更新...",
    update_to: "更新到",
    update_available: "有可用更新",
    update_prompt_now: "版本 {version} 已可用。是否现在更新？",
    exit: "退出",
    show_widget: "任务栏小组件",
    show_floating_monitor: "桌面浮窗",
    detailed_tray_icons: "服务商托盘图标",
    notifications: "通知",
    notify_session_reset: "短期额度重置时通知",
    notify_weekly_reset: "长期额度重置时通知",
    claude_cli_updated_title: "Claude Code 已更新",
    claude_cli_updated_body: "已从 {before} 更新到 {after}，认证已自动恢复。",
    reset_notification_title: "用量窗口已重置",
    reset_notification_body: "{provider} 的 {window} 配额窗口已重置。",
    session_window: "5h",
    weekly_window: "7d",
    quota_window: "额度",
    day_suffix: "天",
    hour_suffix: "小时",
    minute_suffix: "分钟",
    second_suffix: "秒",
    detail_waiting: "等待用量数据",
    detail_unavailable: "无法获取用量数据",
    detail_temporarily_unavailable: "暂时无法获取用量",
    detail_pin_action: "保持详情打开",
    detail_unpin_action: "允许详情自动关闭",
    detail_lock_position_action: "锁定窗口位置",
    detail_unlock_position_action: "允许移动窗口",
    detail_close_action: "关闭详情",
    detail_refreshing: "正在刷新",
    detail_network_action: "请检查网络连接",
    detail_network_outcome: "正在自动重试",
    detail_badge_auth_failed: "认证失败",
    detail_claude_login_action: "请重新登录 Claude",
    detail_sign_in_again_action: "请重新登录 {provider}",
    detail_monitoring_resumes: "登录后自动恢复",
    detail_reset_unavailable: "重置时间未知",
    detail_resets_in: "{duration}后重置",
    detail_resets_now: "即将重置",
    detail_updated_ago: "上次更新于 {ago} 前",
    detail_next_in: "{next}后刷新",
    detail_poll_every: "每{interval}",
    detail_some_not_updated: "部分用量数据未更新",
    detail_all_not_updated: "用量数据均未更新",
    detail_badge_stale: "刷新失败",
    detail_badge_near_limit: "接近上限",
    detail_badge_limit_reached: "已达上限",
    detail_badge_not_signed_in: "未检测到",
    detail_not_signed_in_action: "登录 {provider} 后自动识别",
    detail_access_revoked_hint: "已拒绝访问 {provider}",
    detail_access_revoked_outcome: "可在右键菜单中重新开启",
    provider_detected_title: "已检测到 {provider}",
    provider_detected_body: "可在右键菜单中开启以监控其用量。",
    redetect_providers: "重新探测服务商",
    weekdays: ["周日", "周一", "周二", "周三", "周四", "周五", "周六"],
};
