use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "Actualizar con WinGet";

pub(super) const STRINGS: Strings = Strings {
    locale_name: "es-ES",
    window_title: "Gengchou",
    refresh: "Actualizar",
    refresh_now: "Actualizar ahora",
    one_minute: "1 minuto",
    two_minutes: "2 minutos",
    five_minutes: "5 minutos",
    ten_minutes: "10 minutos",
    fifteen_minutes: "15 minutos",
    thirty_minutes: "30 minutos",
    models: "Proveedores",
    claude_model: "Claude",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    settings: "Configuración",
    settings_storage_failed:
        "No se pudieron guardar la configuración ni los datos de uso en caché.",
    start_with_windows: "Iniciar con Windows",
    widget_default_position: "Posición del widget de la barra de tareas",
    floating_default_position: "Posición de la ventana flotante",
    primary_taskbar_left: "Lado izquierdo de la barra de tareas principal",
    primary_taskbar_right: "Lado derecho de la barra de tareas principal",
    primary_display_bottom_left: "Abajo a la izquierda en la pantalla principal",
    primary_display_bottom_right: "Abajo a la derecha en la pantalla principal",
    language: "Idioma",
    system_default: "Predeterminado del sistema",
    check_for_updates: "Buscar actualizaciones",
    checking_for_updates: "Buscando actualizaciones...",
    updates: "Actualizaciones",
    update_in_progress: "Ya hay una comprobación de actualización en curso.",
    up_to_date: "Ya tienes la versión más reciente.",
    up_to_date_short: "Actualizado",
    update_failed: "No se pudo actualizar automáticamente",
    applying_update: "Aplicando actualización...",
    update_to: "Actualizar a",
    update_available: "Actualización disponible",
    update_prompt_now: "La versión {version} está disponible. ¿Quieres actualizar ahora?",
    exit: "Salir",
    show_widget: "Widget de la barra de tareas",
    show_floating_monitor: "Ventana flotante",
    detailed_tray_icons: "Iconos de proveedores en la bandeja",
    notifications: "Notifications",
    notify_session_reset: "Notificar al reiniciar el límite corto",
    notify_weekly_reset: "Notificar al reiniciar el límite largo",
    notify_claude_cli_update: "Notificar cuando se actualice Claude Code",
    claude_cli_updated_title: "Claude Code actualizado",
    claude_cli_updated_body: "Actualizado de {before} a {after}; autenticación recuperada.",
    reset_notification_title: "Ventana de uso restablecida",
    reset_notification_body: "Se restableció la cuota de {provider} ({window}).",
    session_window: "5h",
    weekly_window: "7d",
    quota_window: "Cuota",
    day_suffix: "d",
    hour_suffix: "h",
    minute_suffix: "m",
    second_suffix: "s",
    detail_waiting: "Esperando datos de uso",
    detail_unavailable: "No se pueden obtener los datos de uso",
    detail_temporarily_unavailable: "Datos de uso no disponibles temporalmente",
    detail_pin_action: "Mantener los detalles abiertos",
    detail_unpin_action: "Permitir el cierre automático",
    detail_lock_position_action: "Bloquear la posición de la ventana",
    detail_unlock_position_action: "Permitir mover la ventana",
    detail_close_action: "Cerrar detalles",
    detail_refreshing: "Actualizando",
    detail_network_action: "Comprueba la conexión",
    detail_network_outcome: "Reintentando automáticamente",
    detail_badge_auth_failed: "Autenticación fallida",
    detail_claude_login_action: "Vuelve a iniciar sesión en Claude",
    detail_sign_in_again_action: "Vuelve a iniciar sesión en {provider}",
    detail_monitoring_resumes: "Se reanuda automáticamente tras iniciar sesión",
    detail_reset_unavailable: "Hora de restablecimiento no disponible",
    detail_resets_in: "Se restablece en {duration}",
    detail_resets_now: "Se restablece ahora",
    detail_updated_ago: "Última actualización hace {ago}",
    detail_next_in: "siguiente en {next}",
    detail_poll_every: "Cada {interval}",
    detail_some_not_updated: "Algunos datos de uso no se actualizaron",
    detail_all_not_updated: "Los datos de uso no se actualizaron",
    detail_badge_stale: "Error de actualización",
    detail_badge_near_limit: "Cerca del límite",
    detail_badge_limit_reached: "Límite alcanzado",
    detail_badge_not_signed_in: "No detectado",
    detail_not_signed_in_action: "Se detecta automáticamente tras iniciar sesión en {provider}",
    detail_access_revoked_hint: "Acceso a {provider} denegado",
    detail_access_revoked_outcome: "Actívalo de nuevo en el menú contextual",
    provider_detected_title: "{provider} detectado",
    provider_detected_body: "Actívalo desde el menú contextual para supervisar su uso.",
    redetect_providers: "Volver a detectar proveedores",
    weekdays: ["dom", "lun", "mar", "mié", "jue", "vie", "sáb"],
};
