use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "透過 WinGet 更新";

pub(super) const STRINGS: Strings = Strings {
    locale_name: "zh-TW",
    window_title: "更籌",
    refresh: "重新整理",
    refresh_now: "立即重新整理",
    one_minute: "1 分鐘",
    two_minutes: "2 分鐘",
    five_minutes: "5 分鐘",
    ten_minutes: "10 分鐘",
    fifteen_minutes: "15 分鐘",
    thirty_minutes: "30 分鐘",
    models: "服務商",
    claude_model: "Claude",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    grok_model: "Grok",
    settings: "設定",
    settings_storage_failed: "無法儲存設定和快取的使用量資料。",
    start_with_windows: "開機時啟動",
    widget_default_position: "工作列小工具位置",
    floating_default_position: "桌面浮窗位置",
    primary_taskbar_left: "主螢幕工作列左側",
    primary_taskbar_right: "主螢幕工作列右側",
    primary_display_bottom_left: "主螢幕左下角",
    primary_display_bottom_right: "主螢幕右下角",
    language: "語言",
    system_default: "系統預設",
    check_for_updates: "檢查更新",
    checking_for_updates: "正在檢查更新...",
    updates: "更新",
    update_in_progress: "已有更新檢查正在進行中。",
    up_to_date: "您已使用最新版本。",
    up_to_date_short: "已是最新",
    update_failed: "無法自動更新",
    applying_update: "正在套用更新...",
    update_to: "更新至",
    update_available: "有可用更新",
    update_prompt_now: "版本 {version} 已可用。是否立即更新？",
    exit: "結束",
    show_widget: "工作列小工具",
    show_floating_monitor: "桌面浮窗",
    detailed_tray_icons: "服務商系統匣圖示",
    notifications: "Notifications",
    notify_session_reset: "短期額度重置時通知",
    notify_weekly_reset: "長期額度重置時通知",
    claude_cli_updated_title: "Claude Code 已更新",
    claude_cli_updated_body: "已從 {before} 更新到 {after}，認證已自動恢復。",
    reset_notification_title: "用量區間已重設",
    reset_notification_body: "{provider} 的 {window} 配額區間已重設。",
    session_window: "5h",
    weekly_window: "7d",
    quota_window: "額度",
    day_suffix: "天",
    hour_suffix: "時",
    minute_suffix: "分",
    second_suffix: "秒",
    detail_waiting: "等待使用量資料",
    detail_unavailable: "無法取得使用量資料",
    detail_temporarily_unavailable: "暫時無法取得使用量",
    detail_pin_action: "保持詳細資料開啟",
    detail_unpin_action: "允許詳細資料自動關閉",
    detail_lock_position_action: "鎖定視窗位置",
    detail_unlock_position_action: "允許移動視窗",
    detail_close_action: "關閉詳細資料",
    detail_refreshing: "正在重新整理",
    detail_network_action: "請檢查網路連線",
    detail_network_outcome: "正在自動重試",
    detail_badge_auth_failed: "驗證失敗",
    detail_claude_login_action: "請重新登入 Claude",
    detail_sign_in_again_action: "請重新登入 {provider}",
    detail_monitoring_resumes: "登入後自動恢復",
    detail_reset_unavailable: "重設時間未知",
    detail_resets_in: "{duration}後重設",
    detail_resets_now: "即將重設",
    detail_updated_ago: "上次更新於 {ago} 前",
    detail_next_in: "{next}後重新整理",
    detail_poll_every: "每{interval}",
    detail_some_not_updated: "部分使用量資料未更新",
    detail_all_not_updated: "使用量資料均未更新",
    detail_badge_stale: "更新失敗",
    detail_badge_near_limit: "接近上限",
    detail_badge_limit_reached: "已達上限",
    detail_badge_not_signed_in: "未偵測到",
    detail_not_signed_in_action: "登入 {provider} 後自動識別",
    detail_access_revoked_hint: "已拒絕存取 {provider}",
    detail_access_revoked_outcome: "可在右鍵選單中重新開啟",
    provider_detected_title: "已偵測到 {provider}",
    provider_detected_body: "可在右鍵選單中開啟以監控其用量。",
    redetect_providers: "重新偵測服務商",
    weekdays: ["週日", "週一", "週二", "週三", "週四", "週五", "週六"],
};
